// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.19.1
// source: grpc/tracker.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TickerManager3Client is the client API for TickerManager3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerManager3Client interface {
	// get a ticker information
	SelectTicker3(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error)
	InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error)
}

type tickerManager3Client struct {
	cc grpc.ClientConnInterface
}

func NewTickerManager3Client(cc grpc.ClientConnInterface) TickerManager3Client {
	return &tickerManager3Client{cc}
}

func (c *tickerManager3Client) SelectTicker3(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager3/SelectTicker3", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager3Client) InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager3/InsertTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager3Client) DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager3/DeleteTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerManager3Server is the server API for TickerManager3 service.
// All implementations must embed UnimplementedTickerManager3Server
// for forward compatibility
type TickerManager3Server interface {
	// get a ticker information
	SelectTicker3(context.Context, *TickerRequest) (*StockInfo, error)
	InsertTicker(context.Context, *StockInfo) (*Status, error)
	DeleteTicker(context.Context, *TickerRequest) (*Status, error)
	mustEmbedUnimplementedTickerManager3Server()
}

// UnimplementedTickerManager3Server must be embedded to have forward compatible implementations.
type UnimplementedTickerManager3Server struct {
}

func (UnimplementedTickerManager3Server) SelectTicker3(context.Context, *TickerRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTicker3 not implemented")
}
func (UnimplementedTickerManager3Server) InsertTicker(context.Context, *StockInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTicker not implemented")
}
func (UnimplementedTickerManager3Server) DeleteTicker(context.Context, *TickerRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicker not implemented")
}
func (UnimplementedTickerManager3Server) mustEmbedUnimplementedTickerManager3Server() {}

// UnsafeTickerManager3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerManager3Server will
// result in compilation errors.
type UnsafeTickerManager3Server interface {
	mustEmbedUnimplementedTickerManager3Server()
}

func RegisterTickerManager3Server(s grpc.ServiceRegistrar, srv TickerManager3Server) {
	s.RegisterService(&TickerManager3_ServiceDesc, srv)
}

func _TickerManager3_SelectTicker3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager3Server).SelectTicker3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager3/SelectTicker3",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager3Server).SelectTicker3(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager3_InsertTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager3Server).InsertTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager3/InsertTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager3Server).InsertTicker(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager3_DeleteTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager3Server).DeleteTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager3/DeleteTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager3Server).DeleteTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerManager3_ServiceDesc is the grpc.ServiceDesc for TickerManager3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerManager3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TickerManager3",
	HandlerType: (*TickerManager3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTicker3",
			Handler:    _TickerManager3_SelectTicker3_Handler,
		},
		{
			MethodName: "InsertTicker",
			Handler:    _TickerManager3_InsertTicker_Handler,
		},
		{
			MethodName: "DeleteTicker",
			Handler:    _TickerManager3_DeleteTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tracker.proto",
}
