// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.19.1
// source: grpc/tracker.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TickerManagerClient is the client API for TickerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerManagerClient interface {
	// get a ticker information
	SelectTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error)
	InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error)
}

type tickerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerManagerClient(cc grpc.ClientConnInterface) TickerManagerClient {
	return &tickerManagerClient{cc}
}

func (c *tickerManagerClient) SelectTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager/SelectTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManagerClient) InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager/InsertTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManagerClient) DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager/DeleteTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerManagerServer is the server API for TickerManager service.
// All implementations must embed UnimplementedTickerManagerServer
// for forward compatibility
type TickerManagerServer interface {
	// get a ticker information
	SelectTicker(context.Context, *TickerRequest) (*StockInfo, error)
	InsertTicker(context.Context, *StockInfo) (*Status, error)
	DeleteTicker(context.Context, *TickerRequest) (*Status, error)
	mustEmbedUnimplementedTickerManagerServer()
}

// UnimplementedTickerManagerServer must be embedded to have forward compatible implementations.
type UnimplementedTickerManagerServer struct {
}

func (UnimplementedTickerManagerServer) SelectTicker(context.Context, *TickerRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTicker not implemented")
}
func (UnimplementedTickerManagerServer) InsertTicker(context.Context, *StockInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTicker not implemented")
}
func (UnimplementedTickerManagerServer) DeleteTicker(context.Context, *TickerRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicker not implemented")
}
func (UnimplementedTickerManagerServer) mustEmbedUnimplementedTickerManagerServer() {}

// UnsafeTickerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerManagerServer will
// result in compilation errors.
type UnsafeTickerManagerServer interface {
	mustEmbedUnimplementedTickerManagerServer()
}

func RegisterTickerManagerServer(s grpc.ServiceRegistrar, srv TickerManagerServer) {
	s.RegisterService(&TickerManager_ServiceDesc, srv)
}

func _TickerManager_SelectTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManagerServer).SelectTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager/SelectTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManagerServer).SelectTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager_InsertTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManagerServer).InsertTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager/InsertTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManagerServer).InsertTicker(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager_DeleteTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManagerServer).DeleteTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager/DeleteTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManagerServer).DeleteTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerManager_ServiceDesc is the grpc.ServiceDesc for TickerManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TickerManager",
	HandlerType: (*TickerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTicker",
			Handler:    _TickerManager_SelectTicker_Handler,
		},
		{
			MethodName: "InsertTicker",
			Handler:    _TickerManager_InsertTicker_Handler,
		},
		{
			MethodName: "DeleteTicker",
			Handler:    _TickerManager_DeleteTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tracker.proto",
}

// TickerManager2Client is the client API for TickerManager2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerManager2Client interface {
	// get a ticker information
	SelectTicker2(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error)
	InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error)
}

type tickerManager2Client struct {
	cc grpc.ClientConnInterface
}

func NewTickerManager2Client(cc grpc.ClientConnInterface) TickerManager2Client {
	return &tickerManager2Client{cc}
}

func (c *tickerManager2Client) SelectTicker2(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager2/SelectTicker2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager2Client) InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager2/InsertTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager2Client) DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager2/DeleteTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerManager2Server is the server API for TickerManager2 service.
// All implementations must embed UnimplementedTickerManager2Server
// for forward compatibility
type TickerManager2Server interface {
	// get a ticker information
	SelectTicker2(context.Context, *TickerRequest) (*StockInfo, error)
	InsertTicker(context.Context, *StockInfo) (*Status, error)
	DeleteTicker(context.Context, *TickerRequest) (*Status, error)
	mustEmbedUnimplementedTickerManager2Server()
}

// UnimplementedTickerManager2Server must be embedded to have forward compatible implementations.
type UnimplementedTickerManager2Server struct {
}

func (UnimplementedTickerManager2Server) SelectTicker2(context.Context, *TickerRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTicker2 not implemented")
}
func (UnimplementedTickerManager2Server) InsertTicker(context.Context, *StockInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTicker not implemented")
}
func (UnimplementedTickerManager2Server) DeleteTicker(context.Context, *TickerRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicker not implemented")
}
func (UnimplementedTickerManager2Server) mustEmbedUnimplementedTickerManager2Server() {}

// UnsafeTickerManager2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerManager2Server will
// result in compilation errors.
type UnsafeTickerManager2Server interface {
	mustEmbedUnimplementedTickerManager2Server()
}

func RegisterTickerManager2Server(s grpc.ServiceRegistrar, srv TickerManager2Server) {
	s.RegisterService(&TickerManager2_ServiceDesc, srv)
}

func _TickerManager2_SelectTicker2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager2Server).SelectTicker2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager2/SelectTicker2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager2Server).SelectTicker2(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager2_InsertTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager2Server).InsertTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager2/InsertTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager2Server).InsertTicker(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager2_DeleteTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager2Server).DeleteTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager2/DeleteTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager2Server).DeleteTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerManager2_ServiceDesc is the grpc.ServiceDesc for TickerManager2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerManager2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TickerManager2",
	HandlerType: (*TickerManager2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTicker2",
			Handler:    _TickerManager2_SelectTicker2_Handler,
		},
		{
			MethodName: "InsertTicker",
			Handler:    _TickerManager2_InsertTicker_Handler,
		},
		{
			MethodName: "DeleteTicker",
			Handler:    _TickerManager2_DeleteTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tracker.proto",
}

// TickerManager3Client is the client API for TickerManager3 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerManager3Client interface {
	// get a ticker information
	SelectTicker3(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error)
	InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error)
}

type tickerManager3Client struct {
	cc grpc.ClientConnInterface
}

func NewTickerManager3Client(cc grpc.ClientConnInterface) TickerManager3Client {
	return &tickerManager3Client{cc}
}

func (c *tickerManager3Client) SelectTicker3(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager3/SelectTicker3", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager3Client) InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager3/InsertTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager3Client) DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager3/DeleteTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerManager3Server is the server API for TickerManager3 service.
// All implementations must embed UnimplementedTickerManager3Server
// for forward compatibility
type TickerManager3Server interface {
	// get a ticker information
	SelectTicker3(context.Context, *TickerRequest) (*StockInfo, error)
	InsertTicker(context.Context, *StockInfo) (*Status, error)
	DeleteTicker(context.Context, *TickerRequest) (*Status, error)
	mustEmbedUnimplementedTickerManager3Server()
}

// UnimplementedTickerManager3Server must be embedded to have forward compatible implementations.
type UnimplementedTickerManager3Server struct {
}

func (UnimplementedTickerManager3Server) SelectTicker3(context.Context, *TickerRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTicker3 not implemented")
}
func (UnimplementedTickerManager3Server) InsertTicker(context.Context, *StockInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTicker not implemented")
}
func (UnimplementedTickerManager3Server) DeleteTicker(context.Context, *TickerRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicker not implemented")
}
func (UnimplementedTickerManager3Server) mustEmbedUnimplementedTickerManager3Server() {}

// UnsafeTickerManager3Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerManager3Server will
// result in compilation errors.
type UnsafeTickerManager3Server interface {
	mustEmbedUnimplementedTickerManager3Server()
}

func RegisterTickerManager3Server(s grpc.ServiceRegistrar, srv TickerManager3Server) {
	s.RegisterService(&TickerManager3_ServiceDesc, srv)
}

func _TickerManager3_SelectTicker3_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager3Server).SelectTicker3(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager3/SelectTicker3",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager3Server).SelectTicker3(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager3_InsertTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager3Server).InsertTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager3/InsertTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager3Server).InsertTicker(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager3_DeleteTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager3Server).DeleteTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager3/DeleteTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager3Server).DeleteTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerManager3_ServiceDesc is the grpc.ServiceDesc for TickerManager3 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerManager3_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TickerManager3",
	HandlerType: (*TickerManager3Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTicker3",
			Handler:    _TickerManager3_SelectTicker3_Handler,
		},
		{
			MethodName: "InsertTicker",
			Handler:    _TickerManager3_InsertTicker_Handler,
		},
		{
			MethodName: "DeleteTicker",
			Handler:    _TickerManager3_DeleteTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tracker.proto",
}

// TickerManager4Client is the client API for TickerManager4 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerManager4Client interface {
	// get a ticker information
	SelectTicker4(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error)
	InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error)
}

type tickerManager4Client struct {
	cc grpc.ClientConnInterface
}

func NewTickerManager4Client(cc grpc.ClientConnInterface) TickerManager4Client {
	return &tickerManager4Client{cc}
}

func (c *tickerManager4Client) SelectTicker4(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager4/SelectTicker4", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager4Client) InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager4/InsertTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager4Client) DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager4/DeleteTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerManager4Server is the server API for TickerManager4 service.
// All implementations must embed UnimplementedTickerManager4Server
// for forward compatibility
type TickerManager4Server interface {
	// get a ticker information
	SelectTicker4(context.Context, *TickerRequest) (*StockInfo, error)
	InsertTicker(context.Context, *StockInfo) (*Status, error)
	DeleteTicker(context.Context, *TickerRequest) (*Status, error)
	mustEmbedUnimplementedTickerManager4Server()
}

// UnimplementedTickerManager4Server must be embedded to have forward compatible implementations.
type UnimplementedTickerManager4Server struct {
}

func (UnimplementedTickerManager4Server) SelectTicker4(context.Context, *TickerRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTicker4 not implemented")
}
func (UnimplementedTickerManager4Server) InsertTicker(context.Context, *StockInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTicker not implemented")
}
func (UnimplementedTickerManager4Server) DeleteTicker(context.Context, *TickerRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicker not implemented")
}
func (UnimplementedTickerManager4Server) mustEmbedUnimplementedTickerManager4Server() {}

// UnsafeTickerManager4Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerManager4Server will
// result in compilation errors.
type UnsafeTickerManager4Server interface {
	mustEmbedUnimplementedTickerManager4Server()
}

func RegisterTickerManager4Server(s grpc.ServiceRegistrar, srv TickerManager4Server) {
	s.RegisterService(&TickerManager4_ServiceDesc, srv)
}

func _TickerManager4_SelectTicker4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager4Server).SelectTicker4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager4/SelectTicker4",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager4Server).SelectTicker4(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager4_InsertTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager4Server).InsertTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager4/InsertTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager4Server).InsertTicker(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager4_DeleteTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager4Server).DeleteTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager4/DeleteTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager4Server).DeleteTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerManager4_ServiceDesc is the grpc.ServiceDesc for TickerManager4 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerManager4_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TickerManager4",
	HandlerType: (*TickerManager4Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTicker4",
			Handler:    _TickerManager4_SelectTicker4_Handler,
		},
		{
			MethodName: "InsertTicker",
			Handler:    _TickerManager4_InsertTicker_Handler,
		},
		{
			MethodName: "DeleteTicker",
			Handler:    _TickerManager4_DeleteTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tracker.proto",
}

// TickerManager5Client is the client API for TickerManager5 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerManager5Client interface {
	// get a ticker information
	SelectTicker5(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error)
	InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error)
	DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error)
}

type tickerManager5Client struct {
	cc grpc.ClientConnInterface
}

func NewTickerManager5Client(cc grpc.ClientConnInterface) TickerManager5Client {
	return &tickerManager5Client{cc}
}

func (c *tickerManager5Client) SelectTicker5(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*StockInfo, error) {
	out := new(StockInfo)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager5/SelectTicker5", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager5Client) InsertTicker(ctx context.Context, in *StockInfo, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager5/InsertTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tickerManager5Client) DeleteTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/grpc.TickerManager5/DeleteTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickerManager5Server is the server API for TickerManager5 service.
// All implementations must embed UnimplementedTickerManager5Server
// for forward compatibility
type TickerManager5Server interface {
	// get a ticker information
	SelectTicker5(context.Context, *TickerRequest) (*StockInfo, error)
	InsertTicker(context.Context, *StockInfo) (*Status, error)
	DeleteTicker(context.Context, *TickerRequest) (*Status, error)
	mustEmbedUnimplementedTickerManager5Server()
}

// UnimplementedTickerManager5Server must be embedded to have forward compatible implementations.
type UnimplementedTickerManager5Server struct {
}

func (UnimplementedTickerManager5Server) SelectTicker5(context.Context, *TickerRequest) (*StockInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectTicker5 not implemented")
}
func (UnimplementedTickerManager5Server) InsertTicker(context.Context, *StockInfo) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTicker not implemented")
}
func (UnimplementedTickerManager5Server) DeleteTicker(context.Context, *TickerRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicker not implemented")
}
func (UnimplementedTickerManager5Server) mustEmbedUnimplementedTickerManager5Server() {}

// UnsafeTickerManager5Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerManager5Server will
// result in compilation errors.
type UnsafeTickerManager5Server interface {
	mustEmbedUnimplementedTickerManager5Server()
}

func RegisterTickerManager5Server(s grpc.ServiceRegistrar, srv TickerManager5Server) {
	s.RegisterService(&TickerManager5_ServiceDesc, srv)
}

func _TickerManager5_SelectTicker5_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager5Server).SelectTicker5(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager5/SelectTicker5",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager5Server).SelectTicker5(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager5_InsertTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager5Server).InsertTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager5/InsertTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager5Server).InsertTicker(ctx, req.(*StockInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TickerManager5_DeleteTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickerManager5Server).DeleteTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.TickerManager5/DeleteTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickerManager5Server).DeleteTicker(ctx, req.(*TickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TickerManager5_ServiceDesc is the grpc.ServiceDesc for TickerManager5 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerManager5_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.TickerManager5",
	HandlerType: (*TickerManager5Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectTicker5",
			Handler:    _TickerManager5_SelectTicker5_Handler,
		},
		{
			MethodName: "InsertTicker",
			Handler:    _TickerManager5_InsertTicker_Handler,
		},
		{
			MethodName: "DeleteTicker",
			Handler:    _TickerManager5_DeleteTicker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/tracker.proto",
}
